### ISSUE TITLE
[Bug]: Background Issue

### ISSUE THREAD

**Issue by faizananwerali** [RickDBCN/filament-email#13]
### What happened?

It does not look good with a transparent background. Ability to add bg-white as background.

I think using Infolist TextEntry here will be more beneficial here.

<img width="1436" alt="Screenshot 2023-08-23 at 9 12 07 PM" src="https://github.com/RickDBCN/filament-email/assets/12691366/d78dcceb-2bee-4c13-866a-d90e848fa973">

### How to reproduce the bug

You can check on your Admin Panel

### Package Version

latest

### PHP Version

v8.1.19

### Laravel Version

v10.14.0

**Comment by RickDBCN** [comment]
Isn't the background white?
What if you change the background of your email, like I do?

![image](https://github.com/RickDBCN/filament-email/assets/9408120/04665ae5-669d-4b20-b2fa-07fcdb55ef7d)

**Comment by faizananwerali** [comment]
Top fieldset doesn't have white background. Also why not use infolist instead of form?

**Comment by RickDBCN** [comment]
Ah I see, do you mind PR'ing this with a screenshot of how it looks like?

**Comment by adamako** [comment]
Hello,
I add company logo in the mail by doing like this
```php 
$message->embed("image_url")
 ```

The image display well in the mail but in filment it's not displayed, how can I solve it ?
@RickDBCN any help ?

<img width="1001" alt="image" src="https://github.com/RickDBCN/filament-email/assets/40002929/c027da93-15ec-4bba-babd-7ec7b576170e">

**Comment by RickDBCN** [comment]
> Hello, I add company logo in the mail by doing like this
> 
> ```
> $message->embed("image_url")
> ```
> 
> The image display well in the mail but in filment it's not displayed, how can I solve it ? @RickDBCN any help ?
> <img alt="image" width="1001" src="https://user-images.githubusercontent.com/40002929/272962421-c027da93-15ec-4bba-babd-7ec7b576170e.png">

Hi Adam! Sorry you've hit this issue.
Could you render the image as HTML?

If not, could you send me the data in the html column in the database?

**Comment by adamako** [comment]
@RickDBCN 

When inspect the element I got this: 
```html
<img src="cid:logo.png" alt="Company Logo" class="w-50 h-50 mx-auto mb-4">
```

How have you achieve yours ? (In your previous message)

**Comment by RickDBCN** [comment]
> @RickDBCN
> 
> When inspect the element I got this:
> 
> ```
> <img src="cid:logo.png" alt="Company Logo" class="w-50 h-50 mx-auto mb-4">
> ```
> 
> How have you achieve yours ? (In your previous message)

It basically saves the HTML and re-renders it on the preview. cid:logo.png is therefor no correct path to the image.
Any chance you can get the logo in your email with HTML instead of using the embed function?

**Comment by adamako** [comment]
@RickDBCN it's work with the image in base64. Thank you
