### ISSUE TITLE
[Bug]: Responsive Layout Issue

### ISSUE THREAD

**Issue by faizananwerali** [RickDBCN/filament-email#14]
### What happened?

It doesn't support a responsive layout yet.

<img width="457" alt="Screenshot 2023-08-23 at 9 13 55 PM" src="https://github.com/RickDBCN/filament-email/assets/12691366/179c16ff-6bc0-42ec-b3cc-7116a21a2fac">

### How to reproduce the bug

check on mobile responsive layout

### Package Version

latest

### PHP Version

v8.1.19

### Laravel Version

v10.14.0

**Comment by RickDBCN** [comment]
I agree! That doesn't look good.
Will be fixed in next update.
