### ISSUE TITLE
Manual delete

### ISSUE THREAD

**Issue by torriv83** [RickDBCN/filament-email#16]
Would be nice to be able to delete emails manually.

**Comment by RickDBCN** [comment]
Hi @torriv83! Do you mean deleting emails from the logbook manually?

**Comment by torriv83** [comment]
Yes :) Now it's only 'preview' and 'send again'.  Would be nice to have a delete button there too. or even better, also have the choice to delete all, or just some.

**Comment by RickDBCN** [comment]
Would a delete bulk action be sufficient? Or would you rather have an action like preview and send again?

**Comment by RickDBCN** [comment]
Hi! I just released a new version which supports bulk delete. #17
