### ISSUE TITLE
Allow us to extend the resource

### ISSUE THREAD

**Issue by quasiperfect** [RickDBCN/filament-email#19]
Please add the resource to the config so we can extend it without problems

**Comment by RickDBCN** [comment]
@quasiperfect Sorry for the late reply. Do you see any chance to PR this? Thanks in advance!

**Comment by quasiperfect** [comment]
@RickDBCN i will try. i managed to have some success on my test instance. the only problem i have is that the `send again` action fails. if i solve it i will make a commit

**Comment by RickDBCN** [comment]
> @RickDBCN i will try. i managed to have some success on my test instance. the only problem i have is that the `send again` action fails. if i solve it i will make a commit

Is the test failing or is the action literally not working?

**Comment by quasiperfect** [comment]
the action but i managed to fix it. i think i can do the pr this weekend

**Comment by RickDBCN** [comment]
Thanks! Would be appreciated :)
