### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by torriv83** [RickDBCN/filament-email#23]
### What happened?

As stated in the discord chat a while back, the Bulk action does not delete.

### How to reproduce the bug

I check all the emails i want to delete, choose bulk action, and then delete. i get a message saying that the records are successfully deleted. but they are not. 

### Package Version

1.0.7

### PHP Version

8.2.0

### Laravel Version

10.28.0

**Comment by RickDBCN** [comment]
Hi Torry,

I need some more time to reproduce this, as I'm unable to reproduce.
I'll get back to you asap.

**Comment by quasiperfect** [comment]
i think i can fix this in the weekend or if is urgent anyone can pr

here
https://github.com/RickDBCN/filament-email/blob/main/src/Filament/Resources/EmailResource.php#L159
we need to add something like 
`->action(fn (Collection $records) => $records->each->delete()),`
see here https://filamentphp.com/docs/3.x/tables/actions#bulk-actions

**Comment by RickDBCN** [comment]
Hmm, I'm confident that the BulkDeleteAction should automatically include the delete for each record. Will need to check.

**Comment by quasiperfect** [comment]
@RickDBCN if you remove ```->action(function () {
                        Notification::make()
                            ->title('Emails succesfully deleted')
                            ->success()
                            ->send();
                    }),``` i think it will work ok. the bulk action already sends a notification

**Comment by torriv83** [comment]
I can confirm that removing the ->action resolves this bug for me. I have never done a PR before, so i'm not sure the step to make a PR.

**Comment by torriv83** [comment]
I tried making a PR. hopefully it works :)

**Comment by RickDBCN** [comment]
> I tried making a PR. hopefully it works :)

It did, thanks!
