### ISSUE TITLE
[Bug]: make navigation group label translatable via __()

### ISSUE THREAD

**Issue by eelco2k** [RickDBCN/filament-email#35]
### What happened?

cannot use other language menu.

### How to reproduce the bug

just install latest version with multiple localisation 

### Package Version

v1.0.11

### PHP Version

8.2.12

### Laravel Version

10.39.0

### Which operating systems does with happen with?

macOS

### Notes

```
public static function getNavigationGroup(): ?string
    {
        return __(Config::get('filament-email.resource.group' ?? parent::getNavigationGroup()));
    }
```

**Comment by RickDBCN** [comment]
Fixed in next release
