### ISSUE TITLE
[Bug]: Emails not logging

### ISSUE THREAD

**Issue by jcsoriano** [RickDBCN/filament-email#37]
### What happened?

When mail notifications are sent, it's not being logged

While debugging, I do `php artisan event:list --event=MessageSent` and the package's listener doesn't show

### How to reproduce the bug

Simply follow the package's Installation instructions

### Package Version

1.0.11

### PHP Version

8.2.8

### Laravel Version

10.43.0

### Which operating systems does with happen with?

macOS

**Comment by jcsoriano** [comment]
After digging further, we found some interesting things:

1. When the package is installed and I do `php artisan event:list`, the things in `EventServiceProvider@listen` array are no longer registered
2. When we uninstall the package and I do `php artisan event:list`, event registration works fine again - i.e. `EventServiceProvider@listen` listeners are registered

**Comment by RickDBCN** [comment]
Hi @jcsoriano,

Any chance you could create a reproduction repository? I'm unable to reproduce this issue myself.
