### ISSUE TITLE
Add the ability to set the FilamentEmailLogger class in the config

### ISSUE THREAD

**Issue by john-aspire** [RickDBCN/filament-email#39]
**Is your feature request related to a problem? Please describe.**
I would like to add extra fields when logging to the database, such as the currently logged on user, etc.

**Describe the solution you'd like**
If I could set the FilamentEmailLogger class in the config, (the same as you've done with EmailResource), then I could add the fields required. 

**Describe alternatives you've considered**
Alternatively you could modify your Email class to look for specific session variables, either fixed or dynamic. Eg. you could: 
 
`public function handle(object $event): void`
`$model::create([`
`...`
`'foreign_id' => session("filament_email_foreign_id")`

You could also have an array of fields to populate in the config file?

**Additional context**
Thank you, for your time!

**Comment by RickDBCN** [comment]
I'm not entirely sure whether or not this should become a config option. Aren't you able to override the FilamentEmailLogger class and extend it with your own logic, for example the fields you want populated?
I feel like saving this data is opinionated and only for specific use cases.

**Comment by john-aspire** [comment]
Hi Rick,

Thanks for your fast response.

I am fairly new to the Laravel/Filament eco system, so perhaps there's a more established way to do it.

Upon a google search I see options such as "AliasLoader", perhaps that's what you're suggesting?

I guess my only point would be that as you have a config file that does similar with other classes, it would be an intuitive and consistent place for me to configure the service.

Thanks again for your efforts.

Regards,

John
________________________________

**Comment by RickDBCN** [comment]
Yeah, I guess the best way is to extend the class and change it yourself.
