### ISSUE TITLE
Publishing assets throws error

### ISSUE THREAD

**Issue by malle-pietje** [RickDBCN/filament-email#5]
### What happened?

Executing the `php artisan` command to publish the assets throws this error:
```sh
$ php artisan vendor:publish --tag="filament-email-migrations"

   INFO  Publishing [filament-email-migrations] assets.

   ERROR  Can't locate path: <vendor/rickdbcn/filament-email/src/../database/migrations/create_femail_table.php.stub>.
```

### How to reproduce the bug

Run the `php artisan` command shown above.

### Package Version

v1.0.1

### PHP Version

8.2.3

### Laravel Version

10.17.1

### Notes

There appears to be a typo here:
```php
->hasMigration('create_femail_table');
```

**Comment by RickDBCN** [comment]
Hi @malle-pietje, thanks for the headsup!
Could you try again with v1.0.2? Does this resolve the issue?

**Comment by malle-pietje** [comment]
Thanks for the very quick turn-around! Appears to be working fine now. Will complete the install 👍
