### ISSUE TITLE
Submit project to madewithlaravel.com

### ISSUE THREAD

**Issue by marcogermani87** [RickDBCN/filament-email#52]
Hi @RickDBCN, i think will be nice to submit project to https://madewithlaravel.com/submit for more visibility of the Laravel community.

**Comment by RickDBCN** [comment]
Do they accept filament plugins?

**Comment by marcogermani87** [comment]
Yes, of course:
- https://madewithlaravel.com/filament-shield
- https://madewithlaravel.com/filament-apex-charts

**Comment by marcogermani87** [comment]
Hi @RickDBCN, any news here?

**Comment by RickDBCN** [comment]
> Hi @RickDBCN, any news here?

Got a bit caught up. Will do this weekend.

**Comment by RickDBCN** [comment]
Submitted @marcogermani87!

**Comment by marcogermani87** [comment]
> Submitted @marcogermani87!

Great @RickDBCN
