### ISSUE TITLE
Update project description and tags

### ISSUE THREAD

**Issue by marcogermani87** [RickDBCN/filament-email#53]
Hi @RickDBCN, you can update this section?

![image](https://github.com/RickDBCN/filament-email/assets/998645/4e0a7f91-ed20-433d-9298-a1fcd584a1d8)

I think can be usefull to add this description, "Log emails in your Filament project" and this tags: "php, laravel, filament, log, email"

Thanks.

**Comment by RickDBCN** [comment]
Hi Marco,
Just updated the description, good catch! :)

**Comment by marcogermani87** [comment]
Hi @RickDBCN, releases section was disappared, you can check?

![image](https://github.com/RickDBCN/filament-email/assets/998645/b81dad67-de4d-4418-91d8-bb26636fc6ae)

**Comment by RickDBCN** [comment]
fixed, sorry
