### ISSUE TITLE
[Bug]: The Update and resend e-mail Action doesn't work if an email has no attachment 

### ISSUE THREAD

**Issue by StaffCollab** [RickDBCN/filament-email#61]
### What happened?

Here is the error: local.ERROR: Undefined array key "attachments"  

### How to reproduce the bug

Just try to click the Update and Resend email button on an email without attachments and see the internal error yourself.

### Package Version

1.4

### PHP Version

8.3

### Laravel Version

10

### Which operating systems does with happen with?

Windows

**Comment by marcogermani87** [comment]
@StaffCollab thanks for reporting. Fixed in v1.4.4
