### ISSUE TITLE
Add support for Shield

### ISSUE THREAD

**Issue by malle-pietje** [RickDBCN/filament-email#7]
**Is your feature request related to a problem? Please describe.**
I always look to control access to resources/pages, Shield is what I'm currently using within Filament.

**Describe the solution you'd like**
The ability to enable support for Shield. For now the plugin doesn't support methods such as `usingPage()` which make it easy to create an override of the default Page class where we can add the `HasPageShield` Trait.

Are there better/easier approaches?

**Comment by RickDBCN** [comment]
Hi @malle-pietje,

If you are using Shield, you could run ```php artisan shield:generate```.
The Email page is just a Filament Resource, therefor Shield should automatically generate new policies, so you are able to control who has access to this resource.

Please let me know if this works for you!

**Comment by malle-pietje** [comment]
Thanks, in that case I need to check Shield which is still allowing access. This my first Filament project after having used several other Laravel packages, so still learning 😉

**Comment by RickDBCN** [comment]
> Thanks, in that case I need to check Shield which is still allowing access. This my first Filament project after having used several other Laravel packages, so still learning 😉

No worries, if you need help, please let me know!
