### ISSUE TITLE
Offer an option to configure table defaultSort

### ISSUE THREAD

**Issue by malle-pietje** [RickDBCN/filament-email#9]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to configure the table `defaultSort` through the config file

**Describe alternatives you've considered**
Overriding the resource would be more of hack, a config option would be nice.

**Additional context**
https://filamentphp.com/docs/3.x/tables/columns/getting-started#sorting-by-default

**Comment by RickDBCN** [comment]
Hi @malle-pietje, I just tagged the latest release v1.0.3 which includes this feature.
Please update your config accordingly.

Thanks!

**Comment by malle-pietje** [comment]
> Hi @malle-pietje, I just tagged the latest release v1.0.3 which includes this feature. Please update your config accordingly.
> 
> Thanks!

Great, thanks for the quick turn-around.

**Comment by malle-pietje** [comment]
I can confirm this option works like a charm!
